### ISSUE TITLE
volume available?

### ISSUE THREAD

**Issue by stkac** [ansrivas/documize#1]
Hi, do you know if possible add a volume on this container?

thanks in advance,

**Comment by ansrivas** [comment]
Hi, this is just the documize server. 
You can add volume on any running container anyways.

**Comment by stkac** [comment]
Hello, yes but where documize store the files what I upload, like .docx .jpg, etc...

I mean where is the path for store local data  on the documize container

**Comment by ansrivas** [comment]
You'd ideally want to attach a database container to this instance and then basically backup the volume of that database container.
for e.g. if you decided to use `postgres` you should ideally backup the data from `/var/lib/postgresql/data` in your running container.

**Comment by stkac** [comment]
Hi, I found the answer to my question here:
https://github.com/documize/community/issues/113#issuecomment-321014873

but now I have other, regarding the performance, which database you think is better for storage hight volume of data, in this case...

thanks in advance,

**Comment by ansrivas** [comment]
@stkac You can refer the example folder to run a local-instance with postgres btw.
